version: '3.9'

services:
  postgres:
    container_name: 'postgres'
    image: postgres:latest
    environment:
       - POSTGRES_USER=USER
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=NAME
    expose:
      - "127.0.0.1:5434"
    ports:
      - "127.0.0.1:5434:5434"
    command: -p 5434
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis:/data
    command: redis-server --save 20 1
    restart: always


volumes:
  postgres:
    driver: local
  redis:
    driver: local
