"""remove time_end from GameDetailSpecifications

Revision ID: 208c08c6c49d
Revises: 8698f6d155a7
Create Date: 2023-03-26 20:39:02.137907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '208c08c6c49d'
down_revision = '8698f6d155a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_detail_specifications', 'time_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_detail_specifications', sa.Column('time_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
