"""fix GameDetail

Revision ID: 6ad84aeaac56
Revises: e609bd8344fe
Create Date: 2023-03-26 20:25:35.718404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad84aeaac56'
down_revision = 'e609bd8344fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_fk', sa.Integer(), nullable=False),
    sa.Column('short_desc', sa.String(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.Column('features', sa.String(), nullable=True),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_fk'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'game_detail_specifications', 'game_details', ['game_detail'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_detail_specifications', type_='foreignkey')
    op.drop_table('game_details')
    # ### end Alembic commands ###
