"""remove time_end from GameDetail

Revision ID: 8698f6d155a7
Revises: 6ad84aeaac56
Create Date: 2023-03-26 20:26:20.769867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8698f6d155a7'
down_revision = '6ad84aeaac56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_details', 'time_end')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_details', sa.Column('time_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
