"""fix GameDetail

Revision ID: e609bd8344fe
Revises: e8b07dfa6d55
Create Date: 2023-03-26 20:23:20.442515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e609bd8344fe'
down_revision = 'e8b07dfa6d55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_detail_specifications', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_detail_specifications', 'type')
    # ### end Alembic commands ###
